// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mseoctogwibdesjmkwbq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1zZW9jdG9nd2liZGVzam1rd2JxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0OTk3MDIsImV4cCI6MjA2MzA3NTcwMn0.BsH3eTwaETWd__BXnF2ZHOW86fo-Clh4k0OMadBn_Bw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);